<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="37384" started-at="2018-07-22T08:01:31Z" finished-at="2018-07-22T08:02:08Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="37384" started-at="2018-07-22T08:01:31Z" finished-at="2018-07-22T08:02:08Z">
      <class name="testPackage.TestClass">
        <test-method status="PASS" signature="testInit()[pri:0, instance:testPackage.TestClass@77cd7a0]" name="testInit" is-config="true" duration-ms="651" started-at="2018-07-22T08:01:31Z" finished-at="2018-07-22T08:01:31Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testInit -->
        <test-method status="PASS" signature="setUpTest(java.lang.reflect.Method)[pri:0, instance:testPackage.TestClass@77cd7a0]" name="setUpTest" is-config="true" duration-ms="18937" started-at="2018-07-22T08:01:31Z" finished-at="2018-07-22T08:01:50Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void testPackage.TestClass.Login() throws java.awt.HeadlessException,java.awt.AWTException,java.io.IOException]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUpTest -->
        <test-method status="FAIL" signature="Login()[pri:1, instance:testPackage.TestClass@77cd7a0]" name="Login" duration-ms="16589" started-at="2018-07-22T08:01:50Z" description="Test to login" finished-at="2018-07-22T08:02:07Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Not back to the previous page. expected [Auckland Deals • GrabOne NZ] but found [Update Account]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Not back to the previous page. expected [Auckland Deals • GrabOne NZ] but found [Update Account]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at pagesPackage.GrabOneHomePage.Login(GrabOneHomePage.java:128)
at testPackage.TestClass.Login(TestClass.java:29)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Login -->
        <test-method status="PASS" signature="tearDownTest(org.testng.ITestResult)[pri:0, instance:testPackage.TestClass@77cd7a0]" name="tearDownTest" is-config="true" duration-ms="1" started-at="2018-07-22T08:02:07Z" finished-at="2018-07-22T08:02:07Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=Login status=FAILURE method=TestClass.Login()[pri:1, instance:testPackage.TestClass@77cd7a0] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDownTest -->
        <test-method status="PASS" signature="clearUp()[pri:0, instance:testPackage.TestClass@77cd7a0]" name="clearUp" is-config="true" duration-ms="1149" started-at="2018-07-22T08:02:07Z" finished-at="2018-07-22T08:02:08Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- clearUp -->
      </class> <!-- testPackage.TestClass -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
